### PR TITLE
Update getServerGroupByName

### PR DESCRIPTION
**Pull request by ventrixcode**
Added getServerGroupByName

### CODE REVIEW

**Comment by Scrumplex** [comment]
First of all: It needs a TS3AsyncApi version too! 
Next: I guess this function is not needed in this api. The user, who uses this api can create this method himself. 
Third: I don't think this method is useful, becausw of the naming of many server groups. I think servergroups should only be identified by id

**Comment by ventrixcode** [comment]
You are right

**Comment by Scrumplex** [comment]
Oh and Fourth: It needs Javadoc

**Comment by TheHolyWaffle** [comment]
It is not the purpose of this api to provide "helper" functions. It should be handled solely as a wrapper around the ts3query api.

**Pull request closed without merging**
