### PR TITLE
Merge pull request #3 from TheHolyWaffle/master

### PR DESCRIPTION
**Pull request by Barofioso**
I want to update my branch, and github is so stupid to merge the fuck branch with my branch!

### CODE REVIEW

**Comment by Firedroide** [comment]
Well, you're doing it wrong :D

Maybe I could help you, just tell me what exactly you're currently doing.

**Comment by Barofioso** [comment]
1. click on pull request
2. i see then this : http://puu.sh/iECJe/2fa2fcecd4.png
3. what should i do now?

**Comment by Firedroide** [comment]
You can't merge our changes into your branch directly on GitHub. You'll need to install a Git client first. Then, add our repository as a remote and finally, pull and merge our master branch into yours.

**Comment by Firedroide** [comment]
Most IDEs also have a Git client already built-in.

More info on adding a remote here: https://help.github.com/articles/adding-a-remote/

More info on pulling from a remote: https://help.github.com/articles/fetching-a-remote/#pull

**Comment by Barofioso** [comment]
http://puu.sh/iEDHc/e37fe24aa1.png
This is my problem now :D

**Comment by Barofioso** [comment]
WOW i did it!

**Comment by Firedroide** [comment]
Congrats! :D

**Pull request closed without merging**
