### PR TITLE
Added an asynchronous implementation of the existing TS3Api, TS3ApiAsync

### PR DESCRIPTION
**Pull request by Firedroide**
Heyo!

I had the week off and decided to spend a bit of time on this API because I'm planning to use it in a project of mine. Specifically, I always felt there had been something missing: full support for asynchronous API calls.

Often, the user doesn't even care about the "result" of a command, e.g. if a text message is broadcasted in a channel. These calls are almost guaranteed to succeed anyway, and if they failed, there wouldn't really be anything that could be done about it. At other times, users want to do API calls but don't really have the time to wait 50ms for the result from the TS server, for example if the API is used inside a game loop.

This is where asynchronous calls come in. Unfortunately, there is almost no support for them in the API, most of the coding work is left up to the user.

Just as a quick example how printing the name of the default channel to the console asynchronously would look like in the existing API:

    final TS3Query query = ...;
    final Runnable r = new Runnable() {
        @Override
        public void run() {
            ChannelInfo channel = query.getChannelInfo(0);
            if (channel != null) {
                System.out.println(channel.getName());
            }
        }
    }
    Thread t = new Thread(r);
    r.start();

... or by using the existing method TS3Query#doCommandAsync(Command, Callback) ...

    final TS3Query query = ...;
    final CChannelInfo info = new CChannelInfo(0);
    query.doCommandAsync(info, new Callback() {
        @Override
        public void handle() {
            if (info.getError().isSuccessful()) {
                ChannelInfo channel = new ChannelInfo(info.getFirstResponse().getMap());
                System.out.println(channel.getName());
            }
        }
    });

As you can see, both methods are clumsy and there's quite a bit of boilerplate code. Therefore I threw together a new class which simplifies this to

    TS3Query query = ...;
    CommandFuture<ChannelInfo> future = query.getAsyncApi().getChannelInfo(0);
    future.onSuccess(new SuccessListener<ChannelInfo>() {
        @Override
        public void handle(ChannelInfo channel) {
            System.out.println(channel.getName());
        }
    });

... or by using Java 8 lambdas ...

    TS3Query query = ...;
    query.getAsyncApi().getChannelInfo(0).onSuccess((c) -> System.out.println(channel.getName()));

This simplifies parallelism by a great amount and also helps users avoid some errors like spawning new Threads for each single command (as done in both old examples above, once explicitly, once implicitly by the API) or forgetting to check whether a command actually succeeded or not.

So, what does this PR actually add?

* Adds a new class called TS3ApiAsync and a getter for it inside the class TS3Query.  
  TS3ApiAsync is basically a copy of TS3Api which returns a Future of the return type instead of the actual return type.
* A class implementing Future that is suited for our needs, CommandFuture.  
  It should have a quite high performance and includes a bunch of utility methods such as forwardResult(CommandFuture) or awaitAll(CommandFuture...)
* A few fixes to the existing API, like removing an infinite loop in banClient(int, String) or finishing the implementation of getPermission()
* Rename the class CClientDBDelelete to CClientDBDelete. This is not entirely related to this PR. It bugged me, but it might break compatibility for a few users. If you deem it not fitting, I will remove this commit.
* Decreasing the time needed to shutdown the connection and cleaned up the code in KeepAliveThread, SocketReader and SocketWriter.  
  This is done by using Thread.interrupt() to terminate the threads instead of having a boolean flag that indicates a shutdown. Thread.interrupt() does actually just that, it sets a boolean flag in the Thread that indicates that the user should shutdown the running task, without actually terminating it by itself. It comes with a little extra feature though, which is that it "wakes up" any Object.wait() and Thread.sleep() calls by throwing an InterruptedException. Knowing this we can replace the numerous calls to Thread.sleep(50) with a single one, waiting for the exact amount of time needed and handling the interrupt by returning from the method.

I am, however, almost certain that I've included some kind of code style error somewhere in the PR, so if something isn't right, just put in a line comment and I'll fix it.

Also, because you haven't included any contribution guidelines and I absolutely despise legal stuff, just let me state this explicitly: I don't care what happens to my code, do with it what you want.

That would be it!
I hope you have a wonderful day!

EDIT: Added a utility method to CommandFuture to determine if the result was successfully set.

### CODE REVIEW

**Comment by TheSaltyWaffle** [comment]
Sorry for the late response. This is great work, thanks.

**Comment by TheHolyWaffle** [comment]
Sorry for the late response. This is great work, thanks.

2015-02-03 21:54 GMT+01:00 TheSaltyWaffle <notifications@github.com>:

**Comment by Firedroide** [comment]
Yay, thank you!

**Comment by TheHolyWaffle** [comment]
I could add you as a collaborator to the project if you want. I've lost interest and you seem to know what you do.

**Comment by Firedroide** [comment]
Sure, I'd love to be added as a collaborator!
I could do some more cleanups and help handle the issues on this repository.

I'm also currently working on adding javadocs to all the API methods and I'm already about 60% done.
What is more, I did a bit of refactoring on the implementation of events over on [/Firedroide/master](https://github.com/Firedroide/TeamSpeak-3-Java-API/), which I would really like you to check out first.

Besides some cleanups, I removed the no-args constructors on the events and used a switch statement instead of a map to get the event class for a given notify... message. I really didn't like how a template object was being used to construct another instance of itself which it would then pass to the listeners.

Unfortunately, the switch statement is still quite verbose. So my question is, do you know of another way to create these event classes without using reflections or byte code manipulation?

**Comment by TheHolyWaffle** [comment]
I don't think a switch is the correct way to go on this. However, this stackoverflow answer provides a clean solution: http://stackoverflow.com/a/3434505

Perhaps pass along the eventData to the create method which passes the data on to the constructor of the event.

**Comment by Firedroide** [comment]
Hmmm...
I checked it out and created a [gist](https://gist.github.com/Firedroide/6537cbf4ceafa8362e6b) about it.

The problem I see with this single-line approach is that it gets really illegible. Sure, it saves one line, but if you're just looking through the code, it gets hard to figure out what's really happening.

The alternative would be a more explicit approach, which doesn't trigger a million checkstyle warnings. The problem with this one is obvious, it's way too long at about 70 lines.

After all I think the switch statement might actually be the way to go. It's overall the cleanest looking of the three approaches, and I manged to squeeze another line out of it, which makes it a little bit less verbose.

Unless we're using reflections, we always have to explicitly tell EventManager which String it should map to which constructor, so we'd need at least one line per event type anyways. And if it's really just about the line count, we could squash each case in the switch statement into a single line without even making it harder to read.

**Comment by TheHolyWaffle** [comment]
You're right, the switch does look better in this situation.

2015-02-06 13:51 GMT+01:00 Firedroide <notifications@github.com>:

**Comment by Firedroide** [comment]
Kay, I'll go commit the switch version then ^^

**Pull request merged**
