### PR TITLE
add utility method ChannelInfo#isEmpty()

### PR DESCRIPTION
**Pull request by Linnun**

### CODE REVIEW

**Comment by Firedroide** [comment]
- Have you already tested if this method works and if it also holds for edge cases? What is the behavior if there are clients in sub-channels?

- Could this method maybe also be added to `Client` via [`getTotalClients`](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/master/src/main/java/com/github/theholywaffle/teamspeak3/api/wrapper/Channel.java#L48)
   - I'm not 100% sure what that getter even returns, so it would have to be tested thoroughly; but it might work :smile: 
   - Speaking of which, could one also add `isFamilyEmpty` via [`getTotalClientsFamily`](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/master/src/main/java/com/github/theholywaffle/teamspeak3/api/wrapper/Channel.java#L44).

- In case this works, it might be also be a good idea to add an abstract method to `ChannelBase` so `isEmpty` could be accessed without knowing if we have a `Channel` / `ChannelInfo`

- Formatting looks good so far :smile:

**Comment by Linnun** [comment]
I did a small test:

```
		Channel x = api.getChannelByNameExact("Zaun", true);
		System.out.println("T: " + x.getTotalClients());
		System.out.println("TF: " + x.getTotalClientsFamily());
		ChannelInfo y = api.getChannelInfo(842);
		System.out.println("S: " + y.getSecondsEmpty());
```

With the following results:

// Nobody in exact channel
T: 0
TF: 0
S: 32

// One client in exact channel
T: 1
TF: 1
S: -1

// One client in sub-channel
T: 0
TF: 1
S: -1



So basically we can use getTotalClients() to reliably check the exact channel, and getTotalClientsFamily() and getSecondsEmpty() to check the entire family of channels (including childs).

This would leave us without a reliable option to find out if an exact channel is empty via ChannelInfo though.

Any ideas for a workaround for ChannelInfo?

**Comment by Firedroide** [comment]
I don't think there is, unfortunately.

However, I was able to find another undocumented flag for `channellist` which we haven't been using yet: `-secondsempty`. So we could just bring a `isFamilyEmpty` method to both `Channel` and `ChannelInfo`.

**Comment by Linnun** [comment]
Oh, that's a channellist parameter? That's why I was so confused over here: #77

**Comment by Firedroide** [comment]
I had already totally forgot about that pull request :open_mouth: 
But yeah, that all makes sense now :smile:

For that `isEmpty` / `isFamilyEmpty` method, the condition should probably also be `>= 0` instead of `> 0`. I was able to get the query to output `[...] seconds_empty=0 [...]` by switching away from the channel and then immediately running the `channellist` command.

**Comment by Linnun** [comment]
I have updated the code. This might be the best we can get out of this.

**Comment by TheHolyWaffle** [comment]
While I do appreciate your suggestion. I would refrain from adding utility
methods in the wrapper classes. In my opinion it's cleaner if those wrapper
classes only serve to get a more easier access to the underlying values.


2016-05-07 20:49 GMT+02:00 Linnun <notifications@github.com>:

**Comment by Firedroide** [comment]
@TheHolyWaffle

But that just leads to more and more boilerplate code in client applications, which I think we should avoid at all costs. Take for instance my last commit, 0a8aa43c278e9fa9de69eedb3fb6f9adf3ddb001, which could basically be considered a utility method. It makes client code much less complex and was thus greatly appreciated by the users.

Of course we must always be aware of feature creep, but I think this method is relatively important for the API because it gives users an easy way to decide if a channel is empty and therefore safe to delete.

While not yet ready to merge (formatting, inheritance, `-secondsempty` option for `channellist`), I'd give  this PR a green light.

**Comment by TheHolyWaffle** [comment]
Alright, you've convinced me because the utility method is using the values
contained in the wrapper. If that wasn' the case than it woul definately
not belong in there. But this isn't the case here. Good to go for me, merge
whenever you want.

2016-05-07 23:23 GMT+02:00 Roger Baumgartner <notifications@github.com>:

**Comment by Firedroide** [comment]
@TheHolyWaffle Thank you very much :smile:

**Comment by Linnun** [comment]
I cleaned up formatting, added inheritance, and added the option for channellist.

I also added ChannelProperty.CHANNEL_DELETE_DELAY, as explained in #99. I have tested the new ChannelProperty.CHANNEL_DELETE_DELAY and it works just fine.

**Comment by Firedroide** [comment]
This is pretty close to perfect, but may I still add two small requests?

1. By adding the "secondsempty" option to `CChannelList`, both `Channel` and `ChannelInfo` should now be able to do `getSecondsEmpty()`; so that method should be moved from `ChannelInfo` to `ChannelBase`. The rest of the implementation is perfect.

2. Currently your PR contains 5 commits for 2 features (secondsempty and channel_delete_delay). I'd be very glad if you could squash these down into 2 commits, one for each feature.

   You could do this with an interactive rebase, but that would be complicated and take too long. It would be much faster to `reset --mixed` onto the commit you've branched out from and then commit `ChannelProperty.java` for the channel_delete_delay feature and then the rest of the files for secondsempty.

Sorry for the inconvenience ^^

**Comment by Linnun** [comment]
Moved the method.

Will try to do a rebase later today, I'm not that familiar with Git yet and don't have much time right now.

**Pull request closed without merging**
