### PR TITLE
Create GitHub actions workflow to replace Travis

### PR DESCRIPTION
**Pull request by rogermb**
Hi @TheHolyWaffle 

Our Travis-CI pipeline seems to have broken, and with the way Travis-CI seems to be heading at the moment (less and less support for free OSS tiers, major security flaws, no new features, and so on), it would make sense to migrate away from Travis and towards GitHub Actions.

I've created a GitHub Actions workflow that should perfectly emulate our old Travis pipeline.

What I'd need you to do is head over to **Settings** > **Secrets** and create the same secret repository variables that are currently available over on Travis. Namely, these are:
- `ENCRYPT_PASSWORD`
- `GPG_KEYNAME`
- `GPG_PASSPHRASE`
- `SONATYPE_USERNAME`
- `SONATYPE_PASSWORD`

Once these are defined, we can merge this pull request, and the resulting GitHub workflow should hopefully just work.
After that's all done, I'll also delete the old .travis.yml and deploy/publish.sh files, which are no longer needed.

Cheers

### CODE REVIEW

**Comment by TheHolyWaffle** [comment]
Hmm, I don't have great news. Just checked the travis-ci project and it seems to have dissappeared on me. All secrets have been wiped and can't seem to find them back

**Comment by rogermb** [comment]
Did you check both https://travis-ci.org/github/TheHolyWaffle/TeamSpeak-3-Java-API and https://app.travis-ci.com/github/TheHolyWaffle/TeamSpeak-3-Java-API? Travis seems to have cloned itself 😄 

But it shouldn't be too much of an issue if the GPG variables and ENCRYPT_PASSWORD are gone. We still need to sign our artifacts to be able to upload them to Maven Central, but you can probably just create a new key pair and upload the new public key to the key servers. Besides, it would probably make sense to rotate the key material after all this time, anyway. There's a good tutorial by Sonatype here: https://central.sonatype.org/publish/requirements/gpg/

After you've created the key pair, you'll have to encrypt them again and upload the encrypted files to `deploy/pubring.gpg.enc` and `deploy/secring.gpg.enc`. Whatever password you use for that encryption (would make sense to use a randomly-generated one, by the way) then needs to be stored in `ENCRYPT_PASSWORD`.

And while you're at it: `openssl` emits this warning when decrypting the key material:

image

So it would probably make sense to also add these arguments to make stuff harder to brute force. Just let me know what `openssl` command you used to encrypt the files so I can make the same changes to the decryption command 😄

**Comment by rogermb** [comment]
Hi @TheHolyWaffle. If you have some spare time, would you mind trying to create a new signing key pair and setting the remaining repository variables? Without a build pipeline in place, we're unable to create new releases of the API and to push artifacts to Maven Central 🙂

**Comment by TheHolyWaffle** [comment]
Hi @rogermb Big thanks for working on this initiative. Apologies for the slow delay, but my job is keeping me busy 24/7 it seems, and I tend to forget about TS3 quite often 😓 

In any case, I've found out about the handy `setup-java` github action steps here, https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-Apache-Maven

They seem to recommend to only specify **2** secrets with regards to gpg: upload the private key and upload the passphrase of that private key. Which is, I think, less hassle to reach the same that we were doing by uploading some encoded files to the repo.

So I did that, I've added those secrets together with the Sonatype credentials. 
image

I think, this should be enough hopefully for you to continue with this PR?

Finally, big thanks for continuing this effort 🙏

**Comment by rogermb** [comment]
Hi @TheHolyWaffle!

Thank you very much for creating the new GPG key! I adapted the GitHub actions workflow to use the new variables, and it worked like a charm. I've already been able to deploy the first snapshot of version 1.4 to Maven Central again 😄 

Speaking of which, thanks for finding that advanced documentation of the `setup-java` action. I was unaware that this action could also be used to import a GPG signing key. It's always cool if we can further standardize our CI/CD pipeline!

And no worries about the delay. I've only just started at my first job a few months ago (working on an Apache Struts 1 application [in 2022](https://struts.apache.org/struts1eol-press), if you can believe it), and despite it just being a "regular 9-to-5 job" without much overtime, I've already noticed how much less time and energy I have to work on FOSS stuff 😓 

Be that as it may, thanks again for your help with this issue, and I truly hope your job will become less stressful and demanding in the future! Cheers!

**Comment by astrolamb-gaming** [comment]
@rogermb (and possibly @TheHolyWaffle) 
I can't seem to find any snapshots of 1.4 on Maven Central yet; is there more work that needs done before this is added? Looking forward to using these fixes on my main projects.

**Comment by rogermb** [comment]
Hi @astrolamb-gaming, nice to hear from you again! 😃 

As far as I'm aware, the snapshots we push to sonatype nexus don't get pushed up to maven central, unlike our releases. So to be able to use any of our snapshot artifacts, you'll have to get them directly from the sonatype snapshots repository, which already contains [a few snapshot builds of version 1.4.0](https://oss.sonatype.org/content/repositories/snapshots/com/github/theholywaffle/teamspeak3-api/1.4.0-SNAPSHOT/). You should add the following repository definition [in your pom.xml or settings.xml](https://maven.apache.org/guides/mini/guide-multiple-repositories.html):

```xml
<repository>
	<id>sonatype-snapshots</id>
	<url>https://oss.sonatype.org/content/repositories/snapshots</url>
	<releases>
		<enabled>false</enabled>
	</releases>
	<snapshots>
		<enabled>true</enabled>
	</snapshots>
</repository>
```

All that said, I should probably really do a release of version 1.4.0 soon. Let's see if I can find some time to work on that in the near future 😅

**Comment by rogermb** [comment]
Hi @astrolamb-gaming, nice to hear from you again! 😃 

As far as I'm aware, the snapshots we push to sonatype nexus don't get pushed up to maven central, unlike our releases. So to be able to use any of our snapshot artifacts, you'll have to get them directly from the sonatype snapshots repository, which already contains [a few snapshot builds of version 1.4.0](https://oss.sonatype.org/content/repositories/snapshots/com/github/theholywaffle/teamspeak3-api/1.4.0-SNAPSHOT/). You should add the following repository definition [in your pom.xml or settings.xml](https://maven.apache.org/guides/mini/guide-multiple-repositories.html):

```xml
<repository>
	<id>sonatype-snapshots</id>
	<url>https://oss.sonatype.org/content/repositories/snapshots</url>
	<releases>
		<enabled>false</enabled>
	</releases>
	<snapshots>
		<enabled>true</enabled>
	</snapshots>
</repository>
```

All that said, I should probably really do a release of version 1.4.0 soon. Let's see if I can find some time to work on that in the near future 😅

**Comment by astrolamb-gaming** [comment]
I actually do already have that snippet in my pom.xml (no idea why... been working on this project for years lol). 
I've changed my dependency version to be "1.4.0-SNAPSHOT".
Anything else I might need to do? I haven't used maven extensively so I'm not familiar with much of its functionality.

**Comment by rogermb** [comment]
If I had to guess, you probably just needed to reload the project in IntelliJ so it knew it had to go fetch the dependencies again 😄 

Either way, great to hear that it's working now.

**Pull request merged**
