### PR TITLE
Merge pull request #3 from TheHolyWaffle/master

### PR DESCRIPTION
**Pull request by Barofioso**
Update test2

### CODE REVIEW

**Comment by Firedroide** [comment]
Heyo!

Please stop creating empty pull requests or at least tell us what exactly it is you're testing with our repository.

**Comment by Barofioso** [comment]
sorry, i want to get your updates, but github won't let me do that, i'm sorry

**Comment by Firedroide** [comment]
Are you using a Git client?

**Comment by Firedroide** [comment]
What I can certainly say is that you're merging the wrong direction. What you want to do is merge our master into your branch, not the other way around.

**Comment by Barofioso** [comment]
yeah i saw that, but i can't change the direction. there isnt a button to switch branches
and no i don't use a git client

**Comment by Firedroide** [comment]
Let's continue discussion on #53.

**Pull request closed without merging**
