### PR TITLE
Bbcode formatter integration

### PR DESCRIPTION
**Pull request by Songbird0**
Hi all!

I've some free time, so I've created a "TeamSpeak-friendly" bbcode formatter.
I propose to integrate it to your TeamSpeak API because that seem pertinent to have all tools at one place. :)

**Note**: All unit tests of all formatter components are written and they're all green!

Regards.

### CODE REVIEW

**Comment by Songbird0** [comment]
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project teamspeak3-api: Unable to generate classpath: org.apache.maven.artifact.resolver.ArtifactResolutionException: Unable to get dependency information for org.apache.maven.surefire:surefire-junit4:jar:2.12.4: Failed to retrieve POM for org.apache.maven.surefire:surefire-junit4:jar:2.12.4: Could not transfer artifact org.apache.maven.surefire:surefire-junit4:pom:2.12.4 from/to central (https://repo.maven.apache.org/maven2): repo.maven.apache.org: Name or service not known
```
Huh? Maven haven't found `junit` ?

**Comment by Kakifrucht** [comment]
Thank you!
However I don't believe this should be included.
Adds a whole lot of bloat for a feature that people could add themselves if necessary and most people wouldn't want.

**Comment by Songbird0** [comment]
Hi!

> Imo you can work well with BBCode already, just by passing them as strings.

Huh, ok, but it is tedious a little bit.

Nevermind, I respect your choice.

Regards.

**Comment by rogermb** [comment]
Well this is unfortunate... I've actually been working on a BB code builder myself, but I never finished the JavaDoc and committed it because I wasn't sure if it would fit in this project and if anyone would ever use it.

I see that you have put a lot of effort into this PR and have even taken the time to write tests and documentation.

But I also feel that your solution is 'overengineered' quite a bit. In my simple mind, something like a BB-Code builder should not take 8 different classes to implement. Then there's the code style issues and the problem of feature scope @Kakifrucht mentioned.

So I think for now, we'll hold off on this PR.
Still, thank you very much for taking the time to send us this :)

**Comment by Songbird0** [comment]
> Then there's the code style issues

What code style issues ? The codacy-bot spots unused instantiations in my unit tests. I've instantiated some objects to generate the class skeleton, that's all.

It's okay, it just was a proposition. :)

**Comment by rogermb** [comment]
Forget about the codacity bot, that thing is not helpful.

I'm talking about stuff like...

- spaces for indentation instead of tabs like the rest of the repository
- `{` on new lines instead of on the same line (Java, not C 😛)
- missing spaces between `if` (or similar keywords) and the parentheses
- missing MIT license header
- author name in the class JavaDoc instead of in the license header
- `@version 0.1.0`
- Having a constructor with varargs and one without (why not just detect if the array is null or empty?)
- `if` without curly brackets and code on a newline.
    This can so easily turn into a bug. Either put the whole statement on 1 line, or put the code on the next line and give it curly brackets.
- `BBcodeFormatter#toBBcodeString()` does the same thing as `BBcodeFormatter#toString()`
- Committing IntelliJ's `teamspeak3-api.iml`
- Committing a change to `.gitignore` without this being the subject of the PR

**Comment by Songbird0** [comment]
`@author` and `@version` are generated by Intellij.

> - Committing IntelliJ's teamspeak3-api.iml
> - Committing a change to .gitignore without this being the subject of the PR

It's a mistake. I've modified `.gitignore` to mask `teamspeak3-api.iml`. This may be undone easily.

> - BBcodeFormatter#toBBcodeString() does the same thing as BBcodeFormatter#toString()

Simply a shortcut. It allow you to write `System.out.println(new BBcodeFormatter("..."))` instead of `System.out.println(new BBcodeFormatter("...").toBBcodeString())`.

Basically, all issues are minor or subjective and may be removed.

**Pull request closed without merging**
